# Generated by Django 5.0.6 on 2024-07-20 14:26

import django.db.models.deletion
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('domain_name', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_title', models.TextField(blank=True, max_length=100, null=True)),
                ('seo_description', models.TextField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('img', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='gt/blog/')),
                ('views', models.IntegerField(default=0)),
                ('read_time', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.category')),
            ],
        ),
    ]
