# Generated by Django 5.0.6 on 2025-01-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alloweddomain',
            name='emails',
            field=models.TextField(blank=True, null=True),
        ),
    ]
