# Generated by Django 5.0.6 on 2024-07-22 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='package',
        ),
        migrations.CreateModel(
            name='ProjectPackagePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('due_date', models.DateTimeField()),
                ('recieve_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projectpackage')),
            ],
        ),
    ]
