# Generated by Django 5.0.6 on 2024-07-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_package_projectpackagepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpackage',
            name='paid',
            field=models.IntegerField(default=0),
        ),
    ]
