# Generated by Django 5.0.6 on 2024-07-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectpackage_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpackagepayment',
            name='due_date',
            field=models.DateField(),
        ),
    ]
