# Generated by Django 5.0.6 on 2024-07-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_projectpackagepayment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpackagepayment',
            name='recieve_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
