# Generated by Django 5.0.6 on 2024-07-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_projectpackagepayment_recieve_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='price',
        ),
        migrations.AddField(
            model_name='projectpackageservice',
            name='price',
            field=models.IntegerField(default=0, help_text='price after discount'),
        ),
        migrations.AlterField(
            model_name='projectpackage',
            name='price',
            field=models.IntegerField(default=0, help_text='price after discount'),
        ),
    ]
