# Generated by Django 5.0.6 on 2024-09-09 11:06

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='official_site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='gt/project/'),
        ),
    ]
