# Generated by Django 5.0.6 on 2025-01-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_technology_official_site_alter_technology_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpackagepayment',
            name='mode',
            field=models.CharField(blank=True, choices=[('online', 'online'), ('cash', 'cash')], max_length=255, null=True),
        ),
    ]
