# Generated by Django 5.0.6 on 2024-08-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAllValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('all_values', models.TextField()),
                ('type', models.CharField(choices=[('tailwind', 'tailwind'), ('daisyui', 'daisyui')], default='tailwind', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
